USE_METIS=1
USE_MKL=1
HSL_AVAIL=1
USE_HWLOC=0

CC = g++

ifeq ($(USE_MKL),1)
    BLASDIR  = /opt/intel/mkl/include/
    BLASLIB  = /opt/intel/mkl/lib/
else
    BLASDIR  = /usr/local/opt/openblas/include/
	BLASLIB  = /usr/local/opt/openblas/lib/
endif

ifeq ($(HSL_AVAIL),1)
	HSLDIR = $(HOME)/Softwares/hsl_mc64-2.3.1/include/
	HSLLIB = $(HOME)/Softwares/hsl_mc64-2.3.1/src
	FORTRANDIR = /usr/local/gfortran/include
	FORTRANLIB = /usr/local/gfortran/lib
endif

EIGENDIR = $(HOME)/Softwares/eigen/
METISDIR = $(HOME)/Softwares/metis/include
METISLIB  = $(HOME)/Softwares/metis/build/Darwin-x86_64/libmetis
PATOHDIR = $(HOME)/Softwares/patoh/Darwin-x86_64
PATOHLIB = $(HOME)/Softwares/patoh/Darwin-x86_64

TTORDIR = $(HOME)/Softwares/tasktorrent/tasktorrent
TTORLIB = $(HOME)/Softwares/tasktorrent/build

HWLOC_INC=-I${HOME}/Softwares/hwloc/build/include
HWLOC_LIBS=-L${HOME}/Softwares/hwloc/build/lib -lhwloc